variables:
  subscriptionID: "16769286-96c0-4610-ba66-b00abde32ac"
  tenantId: "ad15b6de-2280-4c15-949a-b7a6d0e15138"
  environment: "prd"
  azureSubscription: "nza-dbc-prd-sub001-sp001"
  resourceGroupName: "dbc-prd-app-rg001"
  location: "West Europe"
  keyVaultName: "nza-hub-prod-ev-pkv01"
  VnetAddressSpace: "10.100.2.0/24"
  subnetAddressSpaceSQLMI: "10.100.3.0/26"
  subnetAddressSpacePrivateEndpoint: "10.100.4.0/26"
  sqlmiName: "dbc-prd-app-SQLMI001"
  adminObjectId: "65856177-c37e-4731-8221-1ac3d584e3b5"
  storageAccountName: "dbcprdstorage"
  subnetId: "/subscriptions/167e9286-960c-4610-5866-e888abde32ac/resourceGroups/dbc-prd-app-rg001/providers/Microsoft.Network/virtualNetworks/dbc-prd-app-Vnet/subnets/SQLMI-Subnet"
  privateEndpointSubnetId: "/subscriptions/167e9286-96c0-4610-8866-e888abde32ac/resourceGroups/dbc-prd-app-rg001/providers/Microsoft.Network/virtualNetworks/dbc-prd-app-Vnet/subnets/PrivateEndpoint-Subnet"
  dnsZoneSqlMIId: "/subscriptions/167c92a6-9600-4610-5466-2858abde32ac/resourceGroups/dbc-prd-app-rg001/providers/Microsoft.Network/privateDnsZones/privatelink.database.windows.net"
  dnsZoneStorageId: "/subscriptions/167c52a6-96c0-4610-5666-508abde32ac/resourceGroups/dbc-prd-app-rg001/providers/Microsoft.Network/privateDnsZones/privatelink.blob.core.windows.net"
